name: Update arXiv Papers

on:
    workflow_dispatch:  # Enables manual run button
    schedule:
      - cron: '0 0 * * *'  # Runs at midnight UTC  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Latest Papers
        run: |
          curl -s "http://export.arxiv.org/api/query?search_query=all:deep+learning&start=0&max_results=5&sortBy=submittedDate&sortOrder=descending" > papers.xml

      - name: Commit and Push Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase  # Pull latest changes before pushing
          git add papers.xml
          # Check if there are actual changes before committing
          if git diff --cached --quiet; then
            echo "No changes detected"
            exit 0
          fi
          git commit -m "Auto-update arXiv papers"
          git push
